language: csharp
dotnet: 2.0.3
mono: none
sudo: false
cache:
  directories:
  - "$HOME/.nuget/"
before_install:
- set -e
addons:
  apt:
    packages:
    - dotnet-sharedframework-microsoft.netcore.app-1.1.2
script:
- "bash ./$CODEBASE/scripts/build"
